const urduDictionary: { [key: string]: string } = {
  the: 'دی',
  and: 'اور',
  to: 'کو',
  of: 'کا',
  in: 'میں',
  is: 'ہے',
  that: 'کہ',
  a: 'ایک',
  for: 'کے لیے',
  with: 'ساتھ',
  on: 'پر',
  at: 'پر',
  by: 'کے ذریعے',
  from: 'سے',
  up: 'اوپر',
  about: 'کے بارے میں',
  into: 'میں',
  over: 'اوپر',
  after: 'بعد میں',
  before: 'پہلے',
  between: 'درمیان',
  under: 'نیچے',
  through: 'دور',
  during: 'دوران',
  against: 'خلاف',
  among: 'کے درمیان',
  within: 'اندر',
  without: 'بغیر',
  be: 'ہونا',
  have: 'رکھنا',
  do: 'کرنا',
  say: 'کہنا',
  get: 'حاصل کرنا',
  make: 'بنانا',
  go: 'جانا',
  know: 'جاننا',
  think: 'سوچنا',
  take: 'لینا',
  see: 'دیکھنا',
  come: 'آنا',
  want: 'چاہنا',
  use: 'استعمال کرنا',
  find: 'پانا',
  give: 'دینا',
  tell: 'بتانا',
  work: 'کام کرنا',
  seem: 'لگنا',
  feel: 'مہسوس کرنا',
  try: 'کوشش کرنا',
  ask: 'پوچھنا',
  need: 'ضرورت',
  look: 'دیکھنا',
  call: 'کॉल کرنا',
  good: 'اچھا',
  new: 'نیا',
  first: 'پہلا',
  last: 'آخری',
  long: 'لمبا',
  great: 'عظیم',
  little: 'چھوٹا',
  own: 'اپنا',
  other: 'دیگر', // Removed duplicate if it appeared again
  old: 'پرانا',
  right: 'دائیں',
  big: 'بڑا',
  high: 'اونچا',
  different: 'مختلف',
  small: 'چھوٹا',
  large: 'بڑا',
  next: 'اگلا',
  early: 'پہلے',
  young: 'جوان',
  important: 'اہم',
  few: 'کچھ',
  public: 'عام',
  same: 'وہ ہی',
  able: 'قابل',
  also: 'بھی',
  some: 'کچھ',
  very: 'بہت',
  only: 'صرف',
  any: 'کوئی',
  many: 'بہت سارے',
  more: 'مزید',
  most: 'زیادہ تر',
  such: 'ایسا',
  no: 'نہیں',
  yes: 'ہاں',
  not: 'نہیں',
  can: 'سکتا ہے',
  will: 'کرے گا',
  would: 'کرتا',
  should: 'چاہیے',
  could: 'سکتا تھا',
  time: 'وقت',
  year: 'سال',
  day: 'دن',
  week: 'ہفتہ',
  month: 'مہینہ',
  people: 'لوگ',
  man: 'آدمی',
  woman: 'عورت',
  child: 'بچہ',
  house: 'گھر',
  world: 'دنیا',
  life: 'زندگی',
  part: 'حصہ',
  place: 'جگہ',
  case: 'صورتحال',
  point: 'نقطہ',
  fact: 'حقیقت',
  // Add more as needed
};

export function translateToUrdu(text: string): string {
  return text
    .split(' ')
    .map(word => urduDictionary[word.toLowerCase()] || word)
    .join(' ');
}